services:
  user-service:
    container_name: user-service-container
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: user-service:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
     - ${CONTAINER_PORT}:${HOST_PORT}
