-- liquibase formatted sql
--changeset vishnu:change_0001


CREATE TABLE token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token TEXT,
  token_type VARCHAR(255),
  expired BOOLEAN,
  revoked BOOLEAN,
  session_id BIGINT,
  user_id BIGINT,
   created_at BIGINT,
   updated_at BIGINT,
   created_by VARCHAR(255),
   updated_by VARCHAR(255),
  CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token ADD CONSTRAINT fk_token_on_user FOREIGN KEY (user_id) REFERENCES users (id);
